version: '3.8'

services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    env_file:
      - ./env/proxy.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./model:/model
      - ./config:/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "
        source /config/settings.env &&
        python3 -m uvicorn main:app --host 0.0.0.0 --port 8000
      "
